export type Language = {
  id: string
  value: string
  frequent?: boolean
}

export const freqLanguages: Language[] = [
  { id: 'en', value: 'English' },
  { id: 'cy', value: 'Welsh' },
  { id: 'bsl', value: 'British Sign Language (BSL)' },
]

export const languages: Language[] = [
  { id: 'aa', value: 'Afar' },
  { id: 'ab', value: 'Abkhazian' },
  { id: 'ae', value: 'Avestan' },
  { id: 'af', value: 'Afrikaans' },
  { id: 'ak', value: 'Akan' },
  { id: 'am', value: 'Amharic' },
  { id: 'an', value: 'Aragonese' },
  { id: 'ar', value: 'Arabic' },
  { id: 'as', value: 'Assamese' },
  { id: 'av', value: 'Avaric' },
  { id: 'ay', value: 'Aymara' },
  { id: 'az', value: 'Azerbaijani' },
  { id: 'ba', value: 'Bashkir' },
  { id: 'be', value: 'Belarusian' },
  { id: 'bg', value: 'Bulgarian' },
  { id: 'bi', value: 'Bislama' },
  { id: 'bm', value: 'Bambara' },
  { id: 'bn', value: 'Bengali' },
  { id: 'bo', value: 'Tibetan' },
  { id: 'br', value: 'Breton' },
  { id: 'bs', value: 'Bosnian' },
  { id: 'bsl', value: 'British Sign Language (BSL)' },
  { id: 'ca', value: 'Catalan' },
  { id: 'ce', value: 'Chechen' },
  { id: 'ch', value: 'Chamorro' },
  { id: 'co', value: 'Corsican' },
  { id: 'cr', value: 'Cree' },
  { id: 'cs', value: 'Czech' },
  { id: 'cu', value: 'Church Slavic' },
  { id: 'cv', value: 'Chuvash' },
  { id: 'cy', value: 'Welsh' },
  { id: 'da', value: 'Danish' },
  { id: 'de', value: 'German' },
  { id: 'dv', value: 'Divehi' },
  { id: 'dz', value: 'Dzongkha' },
  { id: 'ee', value: 'Ewe' },
  { id: 'el', value: 'Modern Greek' },
  { id: 'en', value: 'English' },
  { id: 'eo', value: 'Esperanto' },
  { id: 'es', value: 'Spanish' },
  { id: 'et', value: 'Estonian' },
  { id: 'eu', value: 'Basque' },
  { id: 'fa', value: 'Persian' },
  { id: 'ff', value: 'Fulah' },
  { id: 'fi', value: 'Finnish' },
  { id: 'fj', value: 'Fijian' },
  { id: 'fo', value: 'Faroese' },
  { id: 'fr', value: 'French' },
  { id: 'fy', value: 'Western Frisian' },
  { id: 'ga', value: 'Irish' },
  { id: 'gd', value: 'Gaelic' },
  { id: 'gl', value: 'Galician' },
  { id: 'gn', value: 'Guarani' },
  { id: 'gu', value: 'Gujarati' },
  { id: 'gv', value: 'Manx' },
  { id: 'ha', value: 'Hausa' },
  { id: 'he', value: 'Hebrew' },
  { id: 'hi', value: 'Hindi' },
  { id: 'ho', value: 'Hiri Motu' },
  { id: 'hr', value: 'Croatian' },
  { id: 'ht', value: 'Haitian' },
  { id: 'hu', value: 'Hungarian' },
  { id: 'hy', value: 'Armenian' },
  { id: 'hz', value: 'Herero' },
  { id: 'ia', value: 'Interlingua' },
  { id: 'id', value: 'Indonesian' },
  { id: 'ie', value: 'Interlingue' },
  { id: 'ig', value: 'Igbo' },
  { id: 'ii', value: 'Sichuan Yi' },
  { id: 'ik', value: 'Inupiaq' },
  { id: 'io', value: 'ido' },
  { id: 'is', value: 'Icelandic' },
  { id: 'it', value: 'Italian' },
  { id: 'iu', value: 'Inuktitut' },
  { id: 'ja', value: 'Japanese' },
  { id: 'jv', value: 'Javanese' },
  { id: 'ka', value: 'Georgian' },
  { id: 'kg', value: 'Kongo' },
  { id: 'ki', value: 'Kikuyu' },
  { id: 'kj', value: 'Kuanyama' },
  { id: 'kk', value: 'Kazakh' },
  { id: 'kl', value: 'Kalaallisut' },
  { id: 'km', value: 'Central Khmer' },
  { id: 'kn', value: 'Kannada' },
  { id: 'ko', value: 'Korean' },
  { id: 'kr', value: 'Kanuri' },
  { id: 'ks', value: 'Kashmiri' },
  { id: 'ku', value: 'Kurdish' },
  { id: 'kv', value: 'Komi' },
  { id: 'kw', value: 'Cornish' },
  { id: 'ky', value: 'Kirghiz' },
  { id: 'la', value: 'Latin' },
  { id: 'lb', value: 'Luxembourgish' },
  { id: 'lg', value: 'Ganda' },
  { id: 'li', value: 'Limburgan' },
  { id: 'ln', value: 'Lingala' },
  { id: 'lo', value: 'Lao' },
  { id: 'lt', value: 'Lithuanian' },
  { id: 'lu', value: 'Luba-Katanga' },
  { id: 'lv', value: 'Latvian' },
  { id: 'mg', value: 'Malagasy' },
  { id: 'mh', value: 'Marshallese' },
  { id: 'mi', value: 'Maori' },
  { id: 'mk', value: 'Macedonian' },
  { id: 'ml', value: 'Malayalam' },
  { id: 'mn', value: 'Mongolian' },
  { id: 'mr', value: 'Marathi' },
  { id: 'ms', value: 'Malay' },
  { id: 'mt', value: 'Maltese' },
  { id: 'my', value: 'Burmese' },
  { id: 'na', value: 'Nauru' },
  { id: 'nb', value: 'Norwegian Bokmål' },
  { id: 'nd', value: 'North Ndebele' },
  { id: 'ne', value: 'Nepali' },
  { id: 'ng', value: 'Ndonga' },
  { id: 'nl', value: 'Dutch' },
  { id: 'nn', value: 'Norwegian Nynorsk' },
  { id: 'no', value: 'Norwegian' },
  { id: 'nr', value: 'South Ndebele' },
  { id: 'nv', value: 'Navajo' },
  { id: 'ny', value: 'Chichewa' },
  { id: 'oc', value: 'Occitan' },
  { id: 'oj', value: 'Ojibwa' },
  { id: 'om', value: 'Oromo' },
  { id: 'or', value: 'Oriya' },
  { id: 'os', value: 'Ossetian' },
  { id: 'pa', value: 'Panjabi' },
  { id: 'pi', value: 'Pali' },
  { id: 'pl', value: 'Polish' },
  { id: 'ps', value: 'Pushto' },
  { id: 'pt', value: 'Portuguese' },
  { id: 'qu', value: 'Quechua' },
  { id: 'rm', value: 'Romansh' },
  { id: 'rn', value: 'Rundi' },
  { id: 'ro', value: 'Romanian' },
  { id: 'ru', value: 'Russian' },
  { id: 'rw', value: 'Kinyarwanda' },
  { id: 'sa', value: 'Sanskrit' },
  { id: 'sc', value: 'Sardinian' },
  { id: 'sd', value: 'Sindhi' },
  { id: 'se', value: 'Northern Sami' },
  { id: 'sg', value: 'Sango' },
  { id: 'si', value: 'Sinhala' },
  { id: 'sk', value: 'Slovak' },
  { id: 'sl', value: 'Slovenian' },
  { id: 'sm', value: 'Samoan' },
  { id: 'sn', value: 'Shona' },
  { id: 'so', value: 'Somali' },
  { id: 'sq', value: 'Albanian' },
  { id: 'sr', value: 'Serbian' },
  { id: 'ss', value: 'Swati' },
  { id: 'st', value: 'Sotho' },
  { id: 'su', value: 'Sundanese' },
  { id: 'sv', value: 'Swedish' },
  { id: 'sw', value: 'Swahili' },
  { id: 'ta', value: 'Tamil' },
  { id: 'te', value: 'Telugu' },
  { id: 'tg', value: 'Tajik' },
  { id: 'th', value: 'Thai' },
  { id: 'ti', value: 'Tigrinya' },
  { id: 'tk', value: 'Turkmen' },
  { id: 'tl', value: 'Tagalog' },
  { id: 'tn', value: 'Tswana' },
  { id: 'to', value: 'Tonga' },
  { id: 'tr', value: 'Turkish' },
  { id: 'ts', value: 'Tsonga' },
  { id: 'tt', value: 'Tatar' },
  { id: 'tw', value: 'Twi' },
  { id: 'ty', value: 'Tahitian' },
  { id: 'ug', value: 'Uighur' },
  { id: 'uk', value: 'Ukrainian' },
  { id: 'ur', value: 'Urdu' },
  { id: 'uz', value: 'Uzbek' },
  { id: 've', value: 'Venda' },
  { id: 'vi', value: 'Vietvaluese' },
  { id: 'vo', value: 'VolapÃ¼k' },
  { id: 'wa', value: 'Walloon' },
  { id: 'wo', value: 'Wolof' },
  { id: 'xh', value: 'Xhosa' },
  { id: 'yi', value: 'Yiddish' },
  { id: 'yo', value: 'Yoruba' },
  { id: 'za', value: 'Zhuang' },
  { id: 'zh', value: 'Chinese' },
  { id: 'zu', value: 'Zulu' },
]
